```{R}
library(DESeq2)
library(magrittr)
library(pheatmap)
library(dendsort)
library(ggplot2)
```

```{R}
run <- function(cmd) {
  cat(">", cmd, "\n", eval(parse(text = cmd)), "\n")
}
```

```{R}
# import, rename column read counts matrix
cts <- as.matrix(
  read.table(
    "outputs/rsem-dmat/all.rcounts.genes.matrix",
    row.names = 1
  )
)
gnames <- colnames(cts) %>% sapply(function(x){strsplit(x, "[.]")[[1]][5]})
colnames(cts) <- gnames

# check dim 
run("dim(cts); # dim before")



# filtering before plotting gene expression heat map
keep <- !rowAlls(cts == 0)
cts <- cts[keep, ]

# check dim 
run("dim(cts); # dim after")
```
Define functions `callback` for reordering clustering object and function `tell_batch` that return batch number according to input group name
```{R}
# define callback function
callback = function(hc, ...){dendsort(hc)}

# define tell_batch function
tell_batch <- function(x){
  ifelse(grepl("CK|LETC|LITR", x), "Batch2", "Batch1")
}

# create column annotation
annotation_col = data.frame(
    Batch = factor(sapply(gnames, tell_batch)) 
)
rownames(annotation_col) = gnames

# create ann_color
ann_colors = list(
    Batch = c(Batch1 = "#1B9E77", Batch2 = "#D95F02")
)
```

```{R}
# sort `cts` by average gene expression level of group "CK"
cts <- cts[
  order(
    cts[, (c("CK_R1", "CK_R2", "CK_R3"))] %>% rowSums,
    decreasing = TRUE
  ),
]
```

Mask genes <= 10 in all sample; sort matrix by CK
```{R}
any_gt10 <- rowAnys(cts > 10)
cts_any_gt10 <- cts[any_gt10, ]
pheatmap(
  log10(cts_any_gt10 + 1),
  annotation_col = annotation_col,
  annotation_colors = ann_colors,
  cluster_rows=FALSE,
  cluster_cols=FALSE,
  show_rownames = FALSE,
  color = colorRampPalette(c("navy", "white", "firebrick3"))(10),
  clustering_callback = callback,
  na_col = "green",
  cutree_cols = 13,
  main = "log10 read counts; mask all <= 10, sort by CK",
  filename = "outputs/rmd-output/ge_heatmap_log10RC_mask=all_lt10_sort_by=CK.png"
)
```

Scale (center) data in columns direction; exclude LITR_R2
```{R}
cts_any_gt10_excl_LITR_R2 <- cts_any_gt10[, gnames[gnames != "LITR_R2"]]
pheatmap(
  log10(cts_any_gt10_excl_LITR_R2 + 1), 
  annotation_col = annotation_col,
  annotation_colors = ann_colors,
  color = colorRampPalette(c("navy", "white", "firebrick3"))(10),
  na_col = "green",
  show_rownames = FALSE,
  scale = "column",
  cluster_rows=FALSE,
  cluster_cols=FALSE,
  clustering_callback = callback,
  cutree_cols = 13,
  main = "log10 read counts; mask all <= 10, sort by CK, scale by col",
  filename = "outputs/rmd-output/ge_heatmap_log10RC_mask=all_lt10_sort_by=CK_exclude=LITR_R2_scale=col.png"
)
```


Scale (center) data in columns direction; exclude LITR_R2; cluster by column
```{R}
pheatmap(
  log10(cts_any_gt10_excl_LITR_R2 + 1), 
  annotation_col = annotation_col,
  annotation_colors = ann_colors,
  color = colorRampPalette(c("navy", "white", "firebrick3"))(10),
  na_col = "green",
  show_rownames = FALSE,
  scale = "column",
  cluster_rows=FALSE,
  cluster_cols=TRUE,
  clustering_callback = callback,
  cutree_cols = 10,
  main = "log10 read counts; mask all <= 10, sort by CK, scale by col",
  filename = "outputs/rmd-output/ge_heatmap_log10RC_mask=all_lt10_sort_by=CK_exclude=LITR_R2_scale=col_cluster_col=T.png"
)
```

# DEA (using `cts_any_gt10_excl_LITR_R2`)
Get condition (as character factor)
```{R}
cts_any_gt10_excl_LITR_R2 <- cts[rowAnys(cts > 10), gnames != "LITR_R2"]

# get conditions from column names
condition <- colnames(cts_any_gt10_excl_LITR_R2) %>% 
  sapply(function(x){strsplit(x, "_")[[1]][1]})

# factorize condition
treatments <- unique(condition)[unique(condition) != "CK"]
condition <- factor(
  condition,
  level = c("CK", treatments)
)
```

Remove column name
```{R}
colnames(cts_any_gt10_excl_LITR_R2) <- NULL
```

Create DESeqDataSet
```{R}
dds <- DESeqDataSetFromMatrix(
  countData = cts_any_gt10_excl_LITR_R2 %>% round,
  colData = DataFrame(condition),
  ~ condition
)
```
DESeq analysis
```{R}
dds <- DESeq(dds)
```
Save DESeq result as RDS
```{R}
saveRDS(dds, file = "outputs/rmd-output/deseq.results.RDS")
```
Show results
```{R}
resultsNames(dds)
```

Get results
```{R}
FDR <- 0.05
FCT <- 1.5
log2fc_mat <- matrix(nrow = nrow(dds), ncol = 0)
pval_mat <- matrix(nrow = nrow(dds), ncol = 0)
cnames <- c()
for (treatment in treatments) {
  res <- results(
    dds,
    alpha = FDR,
    lfcThreshold = FCT,
    contrast = c("condition", treatment, "CK")
  )
  # res <- lfcShrink(
  #   dds,
  #   coef = sprintf("condition_%s_vs_Water", treatment),
  #   type="apeglm"
  # )
  cat("treatment = ", treatment, "control = CK")
  summary(res)

  # add fold change column
  log2fc_mat <- cbind(log2fc_mat, res$log2FoldChange)
  pval_mat <- cbind(pval_mat, res$padj)
  
  # add column name
  cnames <- append(cnames, treatment)
}
colnames(log2fc_mat) <- cnames
rownames(log2fc_mat) <- rownames(dds)
colnames(pval_mat) <- cnames
rownames(pval_mat) <- rownames(dds)
```
Remake column annotation
```{R}
# create column annotation
annotation_col_DEG = data.frame(
    Batch = factor(sapply(cnames, tell_batch)) 
)
rownames(annotation_col_DEG) = cnames

# create ann_color
ann_colors_DEG = list(
    Batch = c(Batch1 = "#1B9E77", Batch2 = "#D95F02")
)
```

Plot log2 fold change
```{R}
# exclude genes not sig in all sample
not_sig_mat <- pval_mat > 0.05
not_sig_mat[is.na(not_sig_mat)] <- TRUE
all_not_sig <- rowAlls(not_sig_mat)
log2fc_mat_any_sig <- log2fc_mat[!all_not_sig, ]


fc_max <- 10
length_out <- fc_max * 2 + 1
pheatmap(
  log2fc_mat_any_sig,
  annotation_colors = ann_colors,
  color = colorRampPalette(c("navy", "white", "firebrick3"))(length_out),
  na_col = "green",
  breaks = seq(-fc_max, fc_max, length.out = length_out),
  show_rownames = FALSE,
  cluster_rows=TRUE,
  cluster_cols=TRUE,
  clustering_callback = callback,
  filename = "outputs/rmd-output/heatmap_log2FC_mask=all_lt10_sort_by=KHY26_exclude=LITR_R2_FDR=0.05_FCT=1.5_cluster=col_row_exclude_all_ns.png"
)
```

Draw volcano plots
```{R}
FDR = .05
FCT = 1.5

df_all <- data.frame()
for (control in levels(condition)) {
  for (treatment in levels(condition)[levels(condition) != control]) {
    res <- results(
      dds,
      alpha = FDR,
      lfcThreshold = FCT,
      contrast = c("condition", treatment, control)
    )
    res_df <- as.data.frame(res)
    res_df$control_cond <- control
    res_df$treatment_cond <- treatment
    
    # add column diffexpressed
    res_df$diffexpressed <- "NO"
    res_df$diffexpressed[res_df$log2FoldChange > FCT & res_df$padj < FDR] <- "UP"
    res_df$diffexpressed[res_df$log2FoldChange < -FCT & res_df$padj < FDR] <- "DOWN"
    
    # add label
    res_df$delabel <- NA
    res_df$delabel[res_df$diffexpressed != "NO"] <- rownames(res_df)[res_df$diffexpressed != "NO"]
    
    df_all <- rbind(df_all, res_df)
  }
}

# # draw
# p <- ggplot(
#   data = res_df,
#   mapping = aes(
#     x = log2FoldChange,
#     y = -log10(padj),
#     col = diffexpressed,
#     label=delabel
#   )
# ) + 
#   geom_point(size=1) +
#   theme_minimal() +
#   ggtitle(paste(treatment, "vs.", control, "FDR < 0.05; |log2FC| > 1.5"))
# 
# # save
# ggplot2::ggsave(
#   filename = sprintf(
#     "outputs/rmd-output/volcano_%s_vs._%s.png",
#     treatment,
#     control
#   ),
#   plot = p
# )
```

```{R}
png(
  filename="outputs/rmd-output/volcano_facet_grid.png",
  width=1000,
  height=1000
)

# draw
ggplot(
 data = df_all,
 mapping = aes(
   x = log2FoldChange,
   y = -log10(padj),
   col = diffexpressed,
   label=delabel
 )
) +
  facet_grid(
    cols = vars(control_cond),
    rows = vars(treatment_cond)
  ) +
  geom_point(size=.5) +
  theme_minimal()

# dev
dev.off()
```

Plot log2 fold change (KHY26, )
```{R}
# exclude genes not sig in all sample
not_sig_mat <- pval_mat > 0.05
not_sig_mat[is.na(not_sig_mat)] <- TRUE
all_not_sig <- rowAlls(not_sig_mat)
log2fc_mat_any_sig <- log2fc_mat[!all_not_sig, ]


fc_max <- 10
length_out <- fc_max * 2 + 1
pheatmap(
  log2fc_mat_any_sig,
  annotation_colors = ann_colors,
  color = colorRampPalette(c("navy", "white", "firebrick3"))(length_out),
  na_col = "green",
  breaks = seq(-fc_max, fc_max, length.out = length_out),
  show_rownames = FALSE,
  cluster_rows=TRUE,
  cluster_cols=TRUE,
  clustering_callback = callback,
  filename = "outputs/rmd-output/heatmap_log2FC_mask=all_lt10_sort_by=KHY26_exclude=LITR_R2_FDR=0.05_FCT=1.5_cluster=col_row_exclude_all_ns.png"
)
```